# Generated by Django 2.0.4 on 2018-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('orderID', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='订单编号')),
                ('star', models.FloatField(verbose_name='星级')),
                ('comment', models.TextField(verbose_name='评价')),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=256, verbose_name='菜名')),
                ('sold', models.IntegerField(verbose_name='卖出')),
            ],
        ),
    ]
