version: "3"
services:

  web:
    build: .
    working_dir: /code/emo
    command: python3 manage.py runserver 0.0.0.0:9000
    volumes:
      - .:/code
    ports:
      - "9000:9000"
    #links:
    #  - db