# Generated by Django 2.0.4 on 2018-05-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DishRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.BigIntegerField(verbose_name='订单号')),
                ('dishID', models.IntegerField(verbose_name='菜编号')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('name', models.CharField(max_length=256, verbose_name='菜名')),
                ('price', models.FloatField(verbose_name='价格')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, verbose_name='用户名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('finished', models.BooleanField(verbose_name='是否完成')),
                ('cancel', models.BooleanField(verbose_name='是否取消')),
                ('note', models.TextField(verbose_name='标注')),
            ],
        ),
    ]
