# Generated by Django 2.0.4 on 2018-05-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='table',
            field=models.IntegerField(default=1, verbose_name='桌号'),
            preserve_default=False,
        ),
    ]
