# Generated by Django 2.0.4 on 2018-06-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dishrecord',
            name='name',
        ),
    ]
