# Generated by Django 2.0.4 on 2018-06-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_dishrecord_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecord',
            name='finished',
            field=models.BooleanField(default=False, verbose_name='是否完成'),
            preserve_default=False,
        ),
    ]
