# Generated by Django 2.0.4 on 2018-06-22 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20180620_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishrecord',
            name='name',
            field=models.TextField(default='unkowndish', verbose_name='菜名'),
            preserve_default=False,
        ),
    ]
