# Generated by Django 2.0.4 on 2018-06-23 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20180623_1318'),
        ('order', '0005_auto_20180620_1453'),
    ]

    operations = [
    ]
