# Generated by Django 2.0 on 2018-06-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wsLogin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxOpenid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=150, verbose_name='openid')),
                ('access_token', models.CharField(max_length=150, verbose_name='access_token')),
            ],
        ),
    ]
