language: python
python:
    - "3.5"
env:
    - DJANGO=2.0
install:
#    - pip install -q Django==$DJANGO --use-mirrors
#    - pip install pep8 --use-mirrors
#    - pip install https://github.com/dcramer/pyflakes/tarball/master
#    - pip install -q -e . --use-mirrors
    - pip install djangorestframework
    - pip install dwebsocket
    - pip install Pillow
#before_script:
#    - "pep8 --exclude=migrations --ignore=E501,E225 src"
#    - pyflakes -x W src
script:
    - python3 manage.py test