# Generated by Django 2.0.4 on 2018-04-15 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('dtype', models.CharField(max_length=256, primary_key=True, serialize=False, verbose_name='类型')),
            ],
        ),
        migrations.CreateModel(
            name='Dishes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='菜名')),
                ('price', models.FloatField(verbose_name='价格')),
                ('description', models.TextField(verbose_name='描述')),
                ('pic', models.ImageField(upload_to='img', verbose_name='图片')),
                ('soldout', models.BooleanField(verbose_name='是否售空')),
                ('recommend', models.BooleanField(verbose_name='是否推荐')),
                ('dtype', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dishes.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dishes', models.TextField(verbose_name='菜名')),
                ('discount', models.FloatField(verbose_name='折扣')),
                ('price', models.FloatField(verbose_name='应付')),
                ('finished', models.BooleanField(verbose_name='是否完成')),
            ],
        ),
    ]
