# Generated by Django 2.0.4 on 2018-04-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('orderID', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='对应订单编号')),
                ('star', models.FloatField(verbose_name='星级')),
                ('comment', models.TextField(verbose_name='评价')),
            ],
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(max_length=256, verbose_name='菜名')),
                ('sold', models.IntegerField(verbose_name='售出数量')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.TextField(default='nothing', verbose_name='备注'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='dishes',
            field=models.TextField(verbose_name='菜名表'),
        ),
    ]
