# Generated by Django 2.0.4 on 2018-04-30 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0002_auto_20180418_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='DishRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderID', models.BigIntegerField(verbose_name='订单编号')),
                ('dishID', models.IntegerField(verbose_name='菜色编号')),
                ('number', models.IntegerField(verbose_name='数量')),
                ('name', models.CharField(max_length=256, verbose_name='菜名')),
                ('price', models.FloatField(verbose_name='价格')),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='dishes',
        ),
    ]
