# Generated by Django 2.0.4 on 2018-05-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dishes', '0003_auto_20180430_1354'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DishRecord',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Statistic',
        ),
    ]
